### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by frvdh** [phamquiluan/Go5-Project#22]
Hey,

Thanks for making this app. Upon running 'docker compose up --build' there was an error the first time concerning opencv: 'ImportError: libGL.so.1: cannot open shared object file: No such file or directory '.

The solution to this bug in my case was to add 'RUN apt-get update && apt-get install ffmpeg libsm6 libxext6 -y' between the lines 'WORKDIR /code' and 'COPY requirements.txt /code' in the Dockerfile of the Streamlit folder.

**Comment by phamquiluan** [comment]
@frvdh could you open a Pull Request :smile:

**Comment by phamquiluan** [comment]
Fixed via #23
